### ISSUE TITLE
How do interface SCIP to Pyomo ?

### ISSUE THREAD

**Issue by luiscarlospxr** [ElsevierSoftwareX/SOFTX-D-20-00087#2]
I read a lot in internet about this topic  but it is not clear how to do it.

Do you have any tutorial to solve the next problem: 

WARNING: Could not locate the 'scipampl' executable, which is required for
    solver scip

ApplicationError: No executable found for solver 'scip'

**Comment by ss391347** [comment]
Hi!

The installation of an optimization programming solver (such as SCIP) goes beyond the scope of the pycity_scheduling package.
However, did you already study the SCIP webpage?
https://www.scipopt.org/
You also need a valid license to run SCIP.
If you are a member of a non-commercial or academic institution, it is free of charge.

Moreover, the repository also includes a Dockerfile with the reference commands for setting up SCIP on a linux-based machine.
https://github.com/ElsevierSoftwareX/SOFTX-D-20-00087/blob/master/gitlab-utils/Dockerfile
